'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace PrintAndExport


    Partial Public Class MainPage

        ''' <summary>
        ''' form control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>

        Protected form_Renamed As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ribbon control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ribbon As Global.DevExpress.Web.ASPxRibbon

        ''' <summary>
        ''' chartControl control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected chartControl As Global.DevExpress.XtraCharts.Web.WebChartControl
    End Class
End Namespace
